baseURL = "https://agitated-kilby-da786e.netlify.com/"
disableKinds = ["section", "page", "taxonomy", "taxonomyTerm"]


[module]
[[module.imports]]
path = "github.com/alpinejs/alpine"
[[module.imports.mounts]]
source = "dist"
target = "assets/js"
[[module.imports]]
path = "github.com/jgthms/bulma"
[[module.imports.mounts]]
source = "bulma.sass"
target = "assets/bulma.sass"
[[module.imports.mounts]]
source = "sass"
target = "assets/sass"
[[module.imports]]
path = "github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
source = "scss"
target = "assets/fontawesome/scss"
[[module.imports.mounts]]
source = "webfonts"
target = "static/webfonts"