baseURL = "https://agitated-kilby-da786e.netlify.com/"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:2006/:01/:02/:title/"

[module]
[[module.imports]]
path="github.com/bep/portable-hugo-links"
[[module.imports]]
path = "github.com/bep/hugo-jslibs/alpinejs_turbolinks"
[[module.imports]]
path = "github.com/jgthms/bulma"
[[module.imports.mounts]]
source = "bulma.sass"
target = "assets/bulma.sass"
[[module.imports.mounts]]
source = "sass"
target = "assets/sass"
[[module.imports]]
path = "github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
source = "scss"
target = "assets/fontawesome/scss"
[[module.imports.mounts]]
source = "webfonts"
target = "static/webfonts"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true